version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: npm run start
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - PORT=3000
      - WEBAPP_PORT=3000
