version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: npm run start
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - PORT=3000
      - WEBAPP_PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

